In [10]:
person='mo'

In [11]:
if person =='omar':
    print("Hello, Omar!")

elif person == 'ali':
    print("Hello, Ali!")
else:
    print("Hello, stranger!")

Hello, stranger!


In [16]:
for i in range(1,6,3):
    print(i)

1
4


In [18]:
x=20
while x>=0:
    print(x)
    x-=5

20
15
10
5
0


In [19]:
x=20
y=x/2

print(f"number of x={x} and number of y ={y}")

number of x=20 and number of y =10.0


In [20]:
name='omar'

In [22]:
print(f"hello mr:{name}")

hello mr:omar


In [29]:
list=[['omar','ahmed','ali'],[1,2,3]]

In [32]:
l={1,2,3,4,5}

In [33]:
print(l)

{1, 2, 3, 4, 5}


In [34]:
store={'apple':10,'orange':5}

In [43]:
print(store.keys())
print(store.values())

dict_keys(['apple', 'orange'])
dict_values([10, 5])


In [50]:
first_name='omar'
last_name='ahmed'

if first_name=='omar':
    if last_name=='ahmed':
        print(f"hello mr :{first_name} {last_name}")

    else : print(f"hello mr {first_name}")

else:
    print("hello kind stranger")





hello mr :omar ahmed


In [51]:
x=5

y=x*2 if x>0 else x*-1

In [52]:
y

10

In [53]:
x=5
y=0

In [57]:
try:
    print(x+y)
    print(x-y)
    print(x*y)
    print(x/y)
    print(x**y)

except:
    print('cant divied by zero')




5
5
0
cant divied by zero


In [ ]:
import pandas as pd
import numpy as np 
from sklearn.linear_model import LinearRegression
X = np.array([[1], [2], [3], [4], [5]])
y = np.array([2, 4, 5, 8, 10])
model = LinearRegression()
model.fit(X, y)
predictions = model.predict(X)
print("Slope:", model.coef_[0])
print("Intercept:", model.intercept_)
print("Predictions:", predictions)

Slope: 2.000000000000001
Intercept: -0.20000000000000284
Predictions: [1.8 3.8 5.8 7.8 9.8]


In [61]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print(mean_absolute_error(y, predictions))
print(mean_squared_error(y, predictions))
print(r2_score(y, predictions))

0.3200000000000003
0.16000000000000006
0.9803921568627451


In [74]:
np.random.seed(0)
np.random.randint(1, 100, size=10)

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [79]:
x=np.linspace(1, 10, num=5)

In [80]:
x

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

array([[[0.6818203 , 0.3595079 , 0.43703195, 0.6976312 , 0.06022547],
        [0.66676672, 0.67063787, 0.21038256, 0.1289263 , 0.31542835],
        [0.36371077, 0.57019677, 0.43860151, 0.98837384, 0.10204481],
        [0.20887676, 0.16130952, 0.65310833, 0.2532916 , 0.46631077],
        [0.24442559, 0.15896958, 0.11037514, 0.65632959, 0.13818295]]])

In [84]:
y

array([[[0.56804456, 0.92559664, 0.07103606],
        [0.0871293 , 0.0202184 , 0.83261985],
        [0.77815675, 0.87001215, 0.97861834],
        [0.79915856, 0.46147936, 0.78052918],
        [0.11827443, 0.63992102, 0.14335329],
        [0.94466892, 0.52184832, 0.41466194]]])